export const GenreOptions = [
  { label: "Todos", value: "todos" },
  { label: "Acción", value: "28" },
  { label: "Aventura", value: "12" },
  { label: "Animación", value: "16" },
  { label: "Comedia", value: "35" },
  { label: "Crimen", value: "80" },
  { label: "Documental", value: "99" },
  { label: "Drama", value: "18" },
  { label: "Fantasía", value: "14" },
  { label: "Historia", value: "36" },
  { label: "Horror", value: "27" },
  { label: "Misterio", value: "9648" },
  { label: "Romance", value: "10749" },
  { label: "Ciencia Ficción", value: "878" },
  { label: "Terror", value: "27" },
  { label: "Guerra", value: "10752" },
  { label: "Western", value: "37" },
  { label: "Familia", value: "10751" },
  { label: "Thiller", value: "53" },
  { label: "Música", value: "10402" },
];

export const DecadeOptions = [
  { label: "Todos", value: "todos" },
  { label: "2020s", value: "2020" },
  { label: "2010s", value: "2010" },
  { label: "2000s", value: "2000" },
  { label: "1990s", value: "1990" },
  { label: "1980s", value: "1980" },
  { label: "1970s", value: "1970" },
  { label: "1960s", value: "1960" },
  { label: "1950s", value: "1950" },
  { label: "1940s", value: "1940" },
  { label: "1930s", value: "1930" },
  { label: "1920s", value: "1920" },
];

export const StreamingServiceOptions = [
  { label: "Todos", value: "" },
  { label: "Netflix", value: "8" },
  { label: "Amazon Prime Video", value: "119" },
  { label: "Hulu", value: "15" },
  { label: "Disney+", value: "337" },
  { label: "HBO Max", value: "384" },
  { label: "Apple TV+", value: "350" },
  { label: "Peacock", value: "386" },
  { label: "Paramount+", value: "531" },
  { label: "YouTube", value: "192" },
  { label: "Google Play Movies", value: "3" },
  { label: "Vudu", value: "7" },
  { label: "Rakuten TV", value: "35" },
  { label: "Filmin", value: "283" },
];
