export const emotionsNames = [
  { name: "Melancolía" },
  { name: "Esperanza" },
  { name: "Tristeza" },
  { name: "Felicidad" },
  { name: "Ansiedad" },
  { name: "Relajación" },
  /*{ name: "Euforia" },
  { name: "Ira" },
  { name: "Sorpresa" },
  { name: "Romántico" },
  { name: "Comedia" },
  { name: "Aventura" },
  { name: "Nostalgia" },
  { name: "Desesperación" },
  { name: "Gravedad" },
  { name: "Inseguridad" },
  { name: "Curiosidad" },
  { name: "Gratitud" },
  { name: "Hopeful Darkness" },
  { name: "Euphoric Sadness" },
  { name: "Heartbroken" },
  { name: "Wonder" },
  { name: "Uncertainty" },
  { name: "Liberation" },
  { name: "Dreamy" },
  { name: "Vulnerable" },
  { name: "Adrenaline Rush" },
  { name: "Cynicism" },
  { name: "Shocked" },*/
];
